### ISSUE TITLE
docker-instructions for Windows

### ISSUE THREAD

**Issue by antoniomedrano** [arogi/arogi-demos#35]
Need to resolve "Getting Started" instruction 2 to work for Windows

**Comment by LEDominator** [comment]
Working on creating a "mclp-web" version that will hopefully allow us to get around this problem.  Apparently this is an issue with using docker on windows and the mapped volume directory in the container must be empty or it causes problems. I'll update with what I find.

http://stackoverflow.com/questions/35315996/how-to-mount-a-docker-volume-while-using-a-windows-host

**Comment by antoniomedrano** [comment]
👍

**Comment by LEDominator** [comment]
I've updated the files to reflect the workaround.
